### ISSUE TITLE
[Marker.io] Report bug about image display

### ISSUE THREAD

**Issue by NTDung93** [NTDung93/zoo-management-fe#22]
[![Screenshot_2023-10-30_07-55-49.png](https://mrkr.io/s/653f61840caa80aeb22fd75d/2)](https://mrkr.io/s/653f61840caa80aeb22fd75d/0)

Steps to reproduce:
- Open web
- Go into page news
- Click on a news to see news's detail
- Scroll down a little bit and see this bug

Actual result:
- Some images are not shown

Expected result:
- All images need to be loaded to UI

---

**Reported by:** John Smith (john@clientwebsite.com) - [Contact via Marker.io](https://app.marker.io/i/653f61840caa80aeb22fd760_9ddaaaae8b15f83b?advanced=1&comments=1)

**Source URL:** [http://localhost:5173/news-detail?id=1](http://localhost:5173/news-detail?id=1)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/653f61840caa80aeb22fd760_9ddaaaae8b15f83b?advanced=1)

**Console:** [ℹ️  1 info 📃  1 log ](https://app.marker.io/i/653f61840caa80aeb22fd760_9ddaaaae8b15f83b?advanced=1&activePane=console)

**Network:** [View network logs](https://app.marker.io/i/653f61840caa80aeb22fd760_9ddaaaae8b15f83b?advanced=1&activePane=console)

**Session replay:** [Watch last 30 seconds](https://app.marker.io/i/653f61840caa80aeb22fd760_9ddaaaae8b15f83b?advanced=1&sessionReplay=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Firefox 119.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1920 x 1080</td></tr><tr><td><strong>OS</strong></td><td>Windows 10</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920 x 955</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

---

**Custom metadata**

- **storeId**: 123
- **storeName**: Organic Fruits

**Comment by NTDung93** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/653f61840caa80aeb22fd760_9ddaaaae8b15f83b) - **Dung Nguyen** commented via Marker.io:

> I dont understand ????

[Reply here](https://app.marker.io/i/653f61840caa80aeb22fd760_9ddaaaae8b15f83b)

**Comment by NTDung93** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/653f61840caa80aeb22fd760_9ddaaaae8b15f83b) - **Thanh Van (tvtvan1407@gmail.com)** commented via Marker.io:

> At the left corner bottom, an image does not work, you need to load it on UI

[Reply here](https://app.marker.io/i/653f61840caa80aeb22fd760_9ddaaaae8b15f83b)

**Comment by Son-2003** [comment]
![397048472_6747632481983716_6872439810540504939_n](https://github.com/NTDung93/zoo-management-fe/assets/113695548/bafd6669-9f59-4544-9562-a497e6ab8cee)

the application cannot the image on ui now please test it again show i can close the issue

**Comment by NTDung93** [comment]
I have checked the problem and it is fixed perfectly. Thank you!

**Comment by NTDung93** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/653f61840caa80aeb22fd760_9ddaaaae8b15f83b) - This issue was marked as **✅ Resolved** in Marker.io
