### ISSUE TITLE
Please fix search feature

### ISSUE THREAD

**Issue by NTDung93** [NTDung93/zoo-management-fe#30]
[![Screenshot_2023-11-03_06-13-57.png](https://mrkr.io/s/65448fa5d62f34f95c812641/2)](https://mrkr.io/s/65448fa5d62f34f95c812641/0)

Steps to reproduce:
- Open home page
- Click on search button in the navbar
Actual result:
- sadfsadf
Expected result:
- asdfsadf

---

**Reported by:** Dung Nguyen (nguyentiendung.2003@gmail.com)

**Source URL:** [http://localhost:5173/?#](http://localhost:5173/?#)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/65448fa5d62f34f95c812644_b6a2befca625c20e?advanced=1)

**Console:** [📃  2 logs ](https://app.marker.io/i/65448fa5d62f34f95c812644_b6a2befca625c20e?advanced=1&activePane=console)

**Network:** [View network logs](https://app.marker.io/i/65448fa5d62f34f95c812644_b6a2befca625c20e?advanced=1&activePane=console)

**Session replay:** [Watch last 30 seconds](https://app.marker.io/i/65448fa5d62f34f95c812644_b6a2befca625c20e?advanced=1&sessionReplay=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Microsoft Edge 120.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1536 x 864</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 (10.0.0)</td></tr><tr><td><strong>Viewport Size</strong></td><td>1389 x 682</td></tr><tr><td><strong>Zoom Level</strong></td><td>110%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.375x</td></tr></table>

**Comment by Son-2003** [comment]
ibfiawbifbawifbiawbf

**Comment by NTDung93** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/65448fa5d62f34f95c812644_b6a2befca625c20e) - This issue was marked as **✅ Resolved** in Marker.io
